apiVersion: v1
kind: Pod
metadata:
  name: helper
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: helper-pvc
          mountPath: /sample
  volumes:
      - name: helper-pvc
        persistentVolumeClaim:
          claimName: csv-report