# Persistent volume mapping a hostPath. Works on 1-node clusters like Minikube
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Mi
  storageClassName: standard
  hostPath:
    # Mount by Minikube from local directory during 'minikube start'
    path: /sample
---
# Persistent Volume Claim required by our batch job
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csv-report
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
  volumeName: sample
